on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dev tools on ${{ matrix.arch }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - base_image: ghcr.io/spack/x86_64_v3-linux-gnu:2024-12-12
            arch: x86_64
            platform: linux/amd64/v3
          - base_image: ghcr.io/spack/aarch64-linux-gnu:v2024-12-18
            arch: aarch64
            platform: linux/aarch64
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          ref: develop
          path: spack

      - name: Run Build
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          base_image: ${{ matrix.base_image }}
          distro: centos-7
          dockerRunArgs: |
            --platform ${{ matrix.platform }}
          env: |
            BASE_IMAGE: ${{ matrix.base_image }}
          run: |
            # Spack environment variables
            export PATH=$PATH:$(pwd)/spack/bin
            export SPACK_COLOR=always
            export SPACK_DISABLE_LOCAL_CONFIG=1
            export SPACK_PYTHON=/opt/python/cp312-cp312/bin/python

            # Spack Install
            spack -e . install -v

            # Push packages and update index
            spack -e . buildcache push --base-image $BASE_IMAGE --update-index local-buildcache
